### ISSUE TITLE
Poor performance of ESlint with tailwind rules

### ISSUE THREAD

**Issue by Codykilpatrick** [spear-ai/citizen#395]
When profiling the forerunner-app directory with:
`TIMING=1 yarn  eslint --max-warnings 0 . `
On a M1 mac It outputs:
```
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
tailwindcss/no-contradicting-classname  |  9409.590 |    42.0%
tailwindcss/enforces-shorthand          |  4583.070 |    20.4%
tailwindcss/classnames-order            |  2386.195 |    10.6%
tailwindcss/no-custom-classname         |  2032.716 |     9.1%
@typescript-eslint/no-misused-promises  |   987.254 |     4.4%
import/namespace                        |   387.072 |     1.7%
@typescript-eslint/no-floating-promises |   286.450 |     1.3%
@typescript-eslint/no-unsafe-assignment |   274.832 |     1.2%
import/no-cycle                         |   185.191 |     0.8%
@typescript-eslint/no-unsafe-argument   |    93.103 |     0.4%
```

This issue appears to be tracked here but is old:
https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/276

**Comment by psirenny** [comment]
Nice find!

**Comment by psirenny** [comment]
Hahahaha @Codykilpatrick I love that you dropped a +1 bomb in the issue and then got downvoted. Taking one for the team 😆.

**Comment by psirenny** [comment]
I disabled those two rules and there's only a marginal performance increase. I think something else might be going on.

**Comment by psirenny** [comment]
Never mind, it's definitely the Tailwind rules.

**Comment by Codykilpatrick** [comment]
>Hahahaha @Codykilpatrick I love that you dropped a +1 bomb in the issue and then got downvoted. Taking one for the team 😆.

My body is a vessel

**Comment by psirenny** [comment]
@Codykilpatrick could you please put this one high up on the priority queue. I want to encourage developers to auto-fix on save.

**Comment by psirenny** [comment]
@minhd-vu I don't know if you're running into this locally, but format-on-save across our projects is SLOW. It's driving me bonkers. @Codykilpatrick has a lot on his plate, so I re-assigned this issue. If you'd like, we can discuss more offline.

**Comment by minhd-vu** [comment]
Hi, an update. I tried out the recomended solution and added this in the `eslint.config.js` in the `dfs` repo:

```javascript
overrides: [
      {
        files: ["**/*.{js,jsx,ts,tsx}"],
        plugins: ["tailwindcss"],
        extends: ["plugin:tailwindcss/recommended"],
        settings: {
          /**
           * Performance issue with the plugin, somewhat mitigated setting cssFiles to an empty array.
           * @see https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/276
           * @see https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/174
           */
          tailwindcss: {
            cssFiles: [],
          },
        },
        rules: {
          "tailwindcss/no-custom-classname": ["warn", options],
          "tailwindcss/no-contradicting-classname": ["warn", options],
          "tailwindcss/classnames-order": ["warn", options],
        },
      },
    ],
```
and it makes it much faster. I'll try to find a way to incorporate this in the `citizen` repo, but I'm not quite sure how to test it. Any thoughts? Would pushing a `dev` tag or something similar to be able to use it in another repo or is there a more optimal way to test.

**Comment by minhd-vu** [comment]
As temp fix y'all can add this to the repos you're working in to improve the performance:
```javascript
const eslintConfig = [
  {
    ignores: [
      "**/.next/*",
      "**/__generated__/*",
      "**/coverage/*",
      "**/data/*",
      "**/dist/*",
      "**/public/*",
      "**/example-data/*",
      "**/exported-schema.mjs",
      "**/graphql/pothos/__generated__",
      "**/messages/__generated__",
      "**/schema.graphql",
      ".benchmark-output.json",
      "next-env.d.ts",
    ],
  },
  ...baseEslintConfig,
  ...nextEslintConfig,
  ...graphqlEslintConfig,
  prettierConfig,
  {
    files: javascriptFamilyFileList,
    rules: {
      // SWC doesn’t support the RegExp `v` flag yet
      // See: https://github.com/swc-project/swc/issues/8462
      "regexp/require-unicode-sets-regexp": ["off"],
    },
    settings: {
      /**
       * Performance issue with the plugin, somewhat mitigated setting cssFiles to an empty array.
       * @see https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/276
       * @see https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/174
       */
      tailwindcss: {
        cssFiles: [],
      },
    },
  },
];
  ```

**Comment by psirenny** [comment]
I wonder if we want to include our global `app.css` file in that list 🤔. That way any custom class names we defined still get discovered.

**Comment by minhd-vu** [comment]
> I wonder if we want to include our global `app.css` file in that list 🤔. That way any custom class names we define still get discovered.

That sounds like a good idea. I'll look into that.
